USE [master]
GO

--FILEGROUPS FÜR SQLDAYS_DBDESIGN


ALTER DATABASE [SQLDAYS_DBDESIGN] ADD FILEGROUP [READING]
GO

ALTER DATABASE [SQLDAYS_DBDESIGN] 
	ADD FILE ( NAME = N'SD_Stammdaten', 
	FILENAME = N'C:\_SQLDB\MSSQL13.MSSQLSERVER\MSSQL\DATA\SD_Stammdaten.ndf' ,
	 SIZE = 8192KB , FILEGROWTH = 65536KB ) 
TO FILEGROUP [READING]
GO


ALTER DATABASE [SQLDAYS_DBDESIGN] ADD FILEGROUP [WRITING]
GO

ALTER DATABASE [SQLDAYS_DBDESIGN]
	 ADD FILE ( NAME = N'SD_WriteData', 
	 FILENAME = N'C:\_SQLDB\MSSQL13.MSSQLSERVER\MSSQL\DATA\SD_WriteData.ndf' , 
	 SIZE = 8192KB , FILEGROWTH = 65536KB ) 
TO FILEGROUP [WRITING]
GO

--TABELLEN auf HDDs verteilen
use SQLDAYS_DBDESIGN;
GO

CREATE TABLE KUNDEN (id int) ON READING

CREATE TABLE Bestellungen (id int) on WRITING


--Wechsel der Dateigruppen
--GUTEN MORGEN.. PLANUNG!!!

USE NORTHWIND

--Wechsel der Orders auf WRTING FGR
USE [master]
GO
ALTER DATABASE [Northwind] ADD FILEGROUP [WRITING]
GO

ALTER DATABASE [Northwind] 
	ADD FILE ( NAME = N'NWwriting', 
	FILENAME = N'C:\_SQLDB\MSSQL13.MSSQLSERVER\MSSQL\DATA\NWwriting.ndf' , 
	SIZE = 8192KB , FILEGROWTH = 65536KB ) 
TO FILEGROUP [WRITING]
GO

--Try translated as "Feig!" ;-)  



